name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:

        - uses: actions/checkout@v4

        - name: Set up Docker
          uses: docker/setup-docker-action@v4

        - name: Set up Docker Compose
          run: docker-compose up --build -d

        - name: Run tests inside container
          run: docker-compose exec -T web python manage.py test

        - name: Format
          run: docker-compose exec -T web black --check .

        - name: Lint
          run: docker-compose exec -T web flake8 .